sudo: required

dist: trusty

services:
  - docker

before_install:
 - docker pull tp33/django
 - docker pull mysql:5.7.17
 - pip install --upgrade pip
 - pip install selenium==3.11.0
 - mkdir db
 - docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v `pwd`/db:/var/lib/mysql  mysql:5.7.17
 - sleep 20
 - docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.17 mysql -uroot -p'$3cureUS' -h db -e "CREATE USER 'www'@'%' IDENTIFIED BY '\$3cureUS'; CREATE DATABASE cs4501 CHARACTER SET utf8; GRANT ALL PRIVILEGES ON *.* TO 'www'@'%';"
 - docker rm mysql-cmdline
 
before_script:
 - docker-compose -f ./docker-compose_TRAVIS.yml up -d
 
script:
  -  docker exec -it cs4501textbookexchange_models_1 bash -c "bash ./tests.sh"
  -  python app/selenium/Selenium.py
  
after_script:
 - docker-compose -f ./docker-compose_TRAVIS.yml stop
 - docker-compose -f ./docker-compose_TRAVIS.yml -f
