models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./app/textbookexchange:/app
    ports:
      - "8001:8000"
    command: bash -c "python manage.py makemigrations myapp && python manage.py makemigrations && python manage.py migrate && python manage.py loaddata dbWithMoreStuff.json && mod_wsgi-express start-server --working-directory . --reload-on-changes ./textbookexchange/wsgi.py"

exp:
    image: tp33/django
    links:
      - models:models-api
    ports:
      - "8002:8000"
    volumes:
      - ./app/experience:/app
    command: bash -c "mod_wsgi-express start-server --working-directory . --reload-on-changes ./experience/wsgi.py"

web:
    image: tp33/django
    links:
      - exp:exp-api
    ports:
      - "8000:8000"
    volumes:
      - ./app/web:/app
    command: bash -c "mod_wsgi-express start-server --working-directory . --reload-on-changes ./web/wsgi.py"
