models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./app/textbookexchange:/app
    ports:
      - "8001:8000"
    command: bash -c "python manage.py makemigrations myapp && python manage.py makemigrations && python manage.py migrate && python manage.py loaddata dbWithMoreStuff.json && mod_wsgi-express start-server --working-directory . --reload-on-changes ./textbookexchange/wsgi.py"

exp:
    image: tp33/django
    links:
      - models:models-api
      - kafka:kafka
      - es:es
    ports:
      - "8002:8000"
    volumes:
      - ./app/experience:/app
    command: bash -c "mod_wsgi-express start-server --working-directory . --reload-on-changes ./experience/wsgi.py"

web:
    image: tp33/django
    links:
      - exp:exp-api
    ports:
      - "8000:8000"
    volumes:
      - ./app/web:/app
    command: bash -c "mod_wsgi-express start-server --working-directory . --reload-on-changes ./web/wsgi.py"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka
   
es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   links:
      - kafka:kafka
      - es:es
   privileged: true
   volumes:
      - ./app/search:/app
   environment:
      - PYTHONUNBUFFERED=0
   command: bash -c "python search_index.py"
   
selenium-chrome:
  image: selenium/standalone-chrome
  container_name: selenium-chrome
  links:
    - web:web
  ports:
    - "4444:4444"

selenium-test:
  image: tp33/django
  container_name: selenium-test
  links:
    - selenium-chrome:selenium-chrome
    - web:web
  volumes:
    - ./app/selenium:/app
  command: bash -c "pip install selenium==3.11.0 && python Selenium.py"
